### ISSUE TITLE
On Link Click 

### ISSUE THREAD

**Issue by BasselFouad** [iGLOO-be/nodemailer-mail-tracking#4]
Could you please give an example of the setup required when using the onLinkClick to apply a callback once a link on the mail is pressed ? 
What I would like to do is update my database whenever a link is clicked on the sent email, yet I have been struggling to do so.

**Comment by LoicMahieu** [comment]
Sorry I am late to response ;) I hope you don't need it anymore since there is a while ;)
What you do in the onLinkClick is your business, I can't give you an example.
