### ISSUE TITLE
does this work for tracking if the recipient uses gmail?

### ISSUE THREAD

**Issue by steven4354** [iGLOO-be/nodemailer-mail-tracking#7]

**Comment by LoicMahieu** [comment]
It'll works when the user agree to display the image, I guess.
If the user click on a link, yes the tracking will be recorded.

**Comment by LoicMahieu** [comment]
@steven4354 

It seems gmail has a special behavior with images, so I could not works.


See: (https://dilshan-h.github.io/Oblivion-Inverse/)


> Since Google uses a special technique, “Image Proxies” to deliver images; this pixel based tracking method is not suitable to gather additional information about the recipients who use G-Mail. Instead of recipient’s IP address and User-Agent, you will receive Google Image Proxy’s UA (User-Agent) and IP address which looks like this:

> Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)

> But, on the bright side, you can still get the resource accessed date and time!
